version: '3.0'
services:
  mysql8:
    image: mysql:8.0 
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=gz4z2b
    volumes:
      - ./script/mysql/:/docker-entrypoint-initdb.d/
    ports:
      - "13316:3306"
    
  redis:
    image: redis:7.2.0
    environment:
      - ALLOW-EMPTY-PASSWORD=yes
    ports:
      - "13317:6379"
