apiVersion: apps/v1
kind: Deployment
metadata:
  name:  webook-mysql
  namespace: default
  labels:
    app:  webook-mysql
spec:
  selector:
    matchLabels:
      app: webook-mysql
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  webook-mysql
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  webook-mysql
        image:  mysql:8.0
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: gz4z2b
        ports:
        - containerPort:  3306
          name:  webook-mysql
      restartPolicy: Always