apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-local-pv
spec:
  storageClassName: mysql-pv
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /mnt/mysql
